import React from 'react'

function Industries() {
    return (
      <>
        <div>Industries</div>
        <p>
          IndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesInIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesInIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustriesIndustries
        </p>
      </>
    );
}

export default Industries